Gift\GeneralBundle\Entity\Config:
    type: entity
    table: null
    repositoryClass: Gift\GeneralBundle\Entity\ConfigRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        value:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    uniqueConstraints:
        name_idx:
            columns: name 
