Gift\GeneralBundle\Entity\Gift:
    type: entity
    table: null
    repositoryClass: Gift\GeneralBundle\Entity\GiftRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        tags:
            type: string
            length: 255
        created_at:
            type: datetime
        premium:
            type: integer
            nullable: true
        popularity7:
            type: integer
            nullable: true
    lifecycleCallbacks: 
        prePersist: [ processPrePersist ]
        postPersist: [ processPostPersist ]
        postUpdate: [ processPostUpdate ]
