Gift\GeneralBundle\Entity\NotifyText:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        text:
            type: text
    lifecycleCallbacks: {  }
