Gift\GeneralBundle\Entity\UserHeart:
    type: entity
    table: null
    indexes:
        user_id_idx:
            columns: [user_id]
        receiver_idx:
            columns: [receiver]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        user_id:
            type: integer
        user_name:
            type: string
            length: 255
        user_box:
            type: string
            length: 255
        user_login:
            type: string
            length: 255
        receiver:
            type: string
            length: 255
        type:
            type: integer
        created_at:
            type: datetime
    lifecycleCallbacks: 
        prePersist: [ processPrePersist ]
        postPersist: [ processPostPersist ]
        postUpdate: [ processPostUpdate ]
