homepage:
    pattern: /
    defaults: { _controller: GiftGeneralBundle:Default:index }

homepage_index:
    pattern: /index
    defaults: { _controller: GiftGeneralBundle:Default:index }

# Admin

admin:
    pattern: /admin 
    defaults: { _controller: GiftGeneralBundle:Admin:admin }

adminAddGift:
    pattern: /admin/gift/add
    defaults: { _controller: GiftGeneralBundle:Admin:gift }

adminEditGift:
    pattern: /admin/gift/{gid}/edit
    defaults: { _controller: GiftGeneralBundle:Admin:gift }

adminGifts:
    pattern: /admin/gifts
    defaults: { _controller: GiftGeneralBundle:Admin:gifts }

adminDeleteGift:
    pattern: /admin/gift/{gid}/delete
    defaults: { _controller: GiftGeneralBundle:Admin:deleteGift }

adminAddCategory:
    pattern: /admin/category/add
    defaults: { _controller: GiftGeneralBundle:Admin:category }

adminEditCategory:
    pattern: /admin/category/{cid}/edit
    defaults: { _controller: GiftGeneralBundle:Admin:category }

adminCategories:
    pattern: /admin/categories
    defaults: { _controller: GiftGeneralBundle:Admin:categories }

adminDeleteCategory:
    pattern: /admin/category/{cid}/delete
    defaults: { _controller: GiftGeneralBundle:Admin:deleteCategory }

adminAddCover:
    pattern: /admin/cover/add
    defaults: { _controller: GiftGeneralBundle:Admin:cover }

adminEditCover:
    pattern: /admin/cover/{cvid}/edit
    defaults: { _controller: GiftGeneralBundle:Admin:cover }

adminCovers:
    pattern: /admin/covers
    defaults: { _controller: GiftGeneralBundle:Admin:covers }

adminDeleteCover:
    pattern: /admin/cover/{cvid}/delete
    defaults: { _controller: GiftGeneralBundle:Admin:deleteCover }

# API

apiGifts:
    pattern: /api/gifts
    defaults: { _controller: GiftGeneralBundle:Default:gifts }

apiCategories:
    pattern: /api/categories
    defaults: { _controller: GiftGeneralBundle:Default:categories }

apiSaveCategoryGift:
    pattern: /api/category/{cid}/gift/{gid}/save
    defaults: { _controller: GiftGeneralBundle:Default:saveCategoryGift }
    requirements:
        _method:  POST

apiCategoryGiftsLite:
    pattern: /api/category/gifts
    defaults: { _controller: GiftGeneralBundle:Default:categoryGifts }

apiCategoryGifts:
    pattern: /api/category/{cid}/gifts
    defaults: { _controller: GiftGeneralBundle:Default:categoryGifts }

apiRemoveCategoryGift:
    pattern: /api/category/{cid}/gift/{gid}/remove
    defaults: { _controller: GiftGeneralBundle:Default:removeCategoryGift }
    requirements:
        _method:  POST

apiUserFriends:
    pattern: /api/user/{sk}/friends
    defaults: { _controller: GiftGeneralBundle:Default:getUserFriends }

apiPurchase:
    pattern: /api/user/{sk}/purchase
    defaults: { _controller: GiftGeneralBundle:Default:purchase }
    requirements:
        _method:  POST

apiUserGifts:
    pattern: /api/user/{sk}/gifts
    defaults: { _controller: GiftGeneralBundle:Default:getUserGifts }

apiOpenGift:
    pattern: /api/user/{sk}/gift/open
    defaults: { _controller: GiftGeneralBundle:Default:openGift }
    requirements:
        _method:  POST

apiPurchases:
    pattern: /api/purchases
    defaults: { _controller: GiftGeneralBundle:Default:purchases }

apiSetGiftPopularity:
    pattern: /api/gift/{gid}/popularity/set
    defaults: { _controller: GiftGeneralBundle:Default:setGiftPopularity }
    requirements:
        _method:  POST

apiBalance:
    pattern: /api/user/balance/increase
    defaults: { _controller: GiftGeneralBundle:Default:increaseBalance }

apiGetBalance:
    pattern: /api/user/{sk}/balance
    defaults: { _controller: GiftGeneralBundle:Default:getBalance }

apiUsers:
    pattern: /api/users
    defaults: { _controller: GiftGeneralBundle:Default:getUsers }

apiUsersCount:
    pattern: /api/users/count
    defaults: { _controller: GiftGeneralBundle:Default:getUsersCount }

apiNotify:
    pattern: /api/user/{uid}/notify/push
    defaults: { _controller: GiftGeneralBundle:Default:notify }
    requirements:
        _method:  POST

apiSendNotify:
    pattern: /api/user/notify/send
    defaults: { _controller: GiftGeneralBundle:Default:sendNotify }
    requirements:
        _method:  POST

apiNotifications:
    pattern: /api/notify
    defaults: { _controller: GiftGeneralBundle:Default:getNotify }

apiGetUid:
    pattern: /api/user/uid
    defaults: { _controller: GiftGeneralBundle:Default:getUid }
    requirements:
        _method:  POST

apiGetHolidays:
    pattern: /api/user/{sk}/holidays
    defaults: { _controller: GiftGeneralBundle:Default:getHolidays }

apiGetUserInfo:
    pattern: /api/user
    defaults: { _controller: GiftGeneralBundle:Default:getUserInfo }

apiSendHeart:
    pattern: /api/user/{sk}/heart/send
    defaults: { _controller: GiftGeneralBundle:Default:sendHeart }
    requirements:
        _method:  POST

apiGetTopFriendsHearts:
    pattern: /api/user/{sk}/heart/top/friends
    defaults: { _controller: GiftGeneralBundle:Default:getFriendsHeartsTop }

apiGetHearts:
    pattern: /api/hearts
    defaults: { _controller: GiftGeneralBundle:Default:getHearts }

apiGetTopHearts:
    pattern: /api/hearts/top
    defaults: { _controller: GiftGeneralBundle:Default:getTopHearts }

apiAddInCircle:
    pattern: /api/user/{sk}/circle/add
    defaults: { _controller: GiftGeneralBundle:Default:addInCircle }
    requirements:
        _method:  POST

apiGetCircle:
    pattern: /api/circle
    defaults: { _controller: GiftGeneralBundle:Default:getCircle }

apiGetConfig:
    pattern: /api/config
    defaults: { _controller: GiftGeneralBundle:Default:getConfig }

apiSendHeartEasy:
    pattern: /api/heart/send
    defaults: { _controller: GiftGeneralBundle:Default:sendHeartEasy }

apiGetLastGivers:
    pattern: /api/user/{sk}/givers
    defaults: { _controller: GiftGeneralBundle:Default:getLastGivers }
