parameters:
#    gift_general.example.class: Gift\GeneralBundle\Example

services:
#    gift_general.example:
#        class: %gift_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
