Gift\GeneralBundle\Entity\Gift:
    properties:
        title:
            - NotBlank: ~
        image_upload:
            - File:
                mimeTypes: [ image/png ]
        thumbnail_upload:
            - File:
                mimeTypes: [ image/png ]
Gift\GeneralBundle\Entity\Cover:
    properties:
        thumbnail_upload:
            - File:
                mimeTypes: [ image/png ]
